### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [bioimage-io/bioengine-web-client#2]
Hi @Nanguage  et al,

great resource here and great that you are maintaining it open source! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by oeway** [comment]
Added a MIT here too, thanks for the heads up!
